### PR TITLE
Update README.md to recommend the GOverlay project

### PR DESCRIPTION
**Pull request by jatin-cbs**
Adding a GOverlay recommendation for vkbasalt GUI :+1:

### CODE REVIEW

**Comment by realmain** [comment]
I don't agree with this pull request.

"Will there be GUI in the future?" "Maybe, but not too soon. But here is a random overlay program that I'm sharing that's unrelated."

**Comment by Faalagorn** [comment]
> I don't agree with this pull request.
> 
> "Will there be GUI in the future?"
> 
> "Maybe, but not too soon. But here is a random overlay program that I'm sharing that's unrelated."

While I get the point, I think that GOverlay has earned it's share of popularity as of lately for it not being random enough.

**Comment by jatin-cbs** [comment]
I have given the rights to edit pull request .. maintainer can edit the text accordingly..

**Comment by TheEvilSkeleton** [comment]
> > I don't agree with this pull request.
> > "Will there be GUI in the future?"
> > "Maybe, but not too soon. But here is a random overlay program that I'm sharing that's unrelated."
> 
> While I get the point, I think that GOverlay has earned it's share of popularity as of lately for it not being random enough.

I agree with this. GOverlay is easy to use and helps the user a lot. It has also been mentioned by GamingOnLinux multiple times. It's really a great program.

**Comment by DadSchoorse** [comment]
I never used GOverlay, and I kinda agree with @realmain that it's not relevant information.

**Comment by Krutonium** [comment]
I disagree about it not being relevant. Until your own application has a UI, this is by far the easiest way for someone who would otherwise be unable to (scared of/unable to find/cant work out how) edit the config. It makes it easier and more convenient, and frankly in my opinion you're dismissing it out of hand.

**Comment by realmain** [comment]
> I disagree about it not being relevant. Until your own application has a UI, this is by far the easiest way for someone who would otherwise be unable to (scared of/unable to find/cant work out how) edit the config. It makes it easier and more convenient, and frankly in my opinion you're dismissing it out of hand.

Looking at the project, I don't understand how it's relevant. 

Please explain in detail how the GOverlay integrates the direct usage of vkBasalt itself.

**Pull request closed without merging**
