### PR TITLE
Added Meson build system support

### PR DESCRIPTION
**Pull request by xvitaly**
Added Meson build system support.

### CODE REVIEW

**Comment by xvitaly** [comment]
Also path to shader file should be extracted from src/basalt.cpp#L25.

**Comment by DadSchoorse** [comment]
I do not know if I want a build system I do not use.

**Comment by xvitaly** [comment]
Now you don't use build system at all. Meson is much more better and will solve most of problems during build and install.

Now project can be easily built and installed on any GNU/Linux distributions.

**Comment by DadSchoorse** [comment]
I do have make and simply speaking: It works, I do not need to modify it when I am adding new cpp or glsl files and I do not know to use and write meson. Maybe in the future I will reconsider this, but for now I simply see no reason to do so.

**Comment by stephanlachnit** [comment]
> Maybe in the future I will reconsider this, but for now I simply see no reason to do so.

One reason are distribution packages. The current makefile makes this impossible, one could patch it to work but in the end once Meson is set in place, it's way easier to work with than make IMHO.

**Pull request closed without merging**
